### ISSUE TITLE
Try Gaussian elimination method

### ISSUE THREAD

**Issue by cloudy-sfu** [AceDroidX/genshin-puzzle#2]
You can use the Gaussian elimination method to solve this puzzle, instead of the proof by exhaustion.

你可以使用列主元高斯消去法解方程，而不必是穷举法。

**Comment by stefnotch** [comment]
There is a simpler approach: Try out *all* possibilities in a breadth-first manner. Since puzzles in Genshin Impact are very small, this can be done in milliseconds.

See: https://github.com/mgatelabs/GenshinSolvers/issues/1
